version: '3'

services:
  web:
    build: .
    environment:
      DJANGO_SUPERUSER_USERNAME: demooleg
      DJANGO_SUPERUSER_PASSWORD: test123
      DJANGO_SUPERUSER_EMAIL: demooleg@example.com
    command: >-
        bash -c 'python manage.py createsuperuser --no-input
        ; python manage.py makemigrations
        && python manage.py migrate
        && gunicorn biblioteka.wsgi
        --bind 0.0.0.0:8020
        --workers 3
        --access-logfile -
        --access-logformat '\''%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s"
        "%({host}i)s" "%({x-forwarded-for}i)s"'\''
        & daphne biblioteka.asgi:application --bind 0.0.0.0 --port 8010'
#        && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/biblioteka
    expose:
      - 8010
      - 8020
    networks:
      - main
    depends_on:
      - db
      - queue
  db:
    image:
      postgres
    environment:
      POSTGRES_PASSWORD: test123
    ports:
      - 5432:5432
    networks:
      - main
  queue:
    image:
      redis
    networks:
      - main
  reverse_proxy:
    build:
      context: .
      dockerfile:
        Dockerfile-reverse_proxy
    ports:
      - 8030:80
    networks:
      - main
    depends_on:
      - web
networks:
  main: