name: Django CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Run asyncio pytests
      run: |
        docker run -p 6379:6379 -d redis:5
        pytest --ds=biblioteka.settings.local_django_development_server
    - name: Deploy to Dockerhub
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        docker build --file Dockerfile --tag ${DOCKER_USERNAME}/biblioteka_web:(date +%s) .
        docker push ${DOCKER_USERNAME}/biblioteka:(date +%s)
        docker build --file Dockerfile-reverse_proxy --tag ${DOCKER_USERNAME}/biblioteka_reverse_proxy:(date +%s) .
        docker push ${DOCKER_USERNAME}/biblioteka:(date +%s)
      env:
        DOCKER_USERNAME: olegkishenkov
        DOCKER_PASSWORD: Apriil_Mh10

